# Generated by Django 4.1.1 on 2022-10-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_subscriber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Підпищик', 'verbose_name_plural': 'Підпищики'},
        ),
    ]
